### ISSUE TITLE
Duplicate Windows tarball

### ISSUE THREAD

**Issue by halldc** [conda-forge/r-digest-feedstock#6]
Issue:
There are two versions of the `win-64/r-digest-0.6.16-r351h301d43c_0.tar.bz2` tarball found [here](https://anaconda.org/conda-forge/r-digest/files).

I think this causes the following error:
```bash
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/win-64/r-digest-0.6.16-r351h301d43c_0.tar.bz2'.
  download saved to: C:\Miniconda36-x64\pkgs\r-digest-0.6.16-r351h301d43c_0.tar.bz2
  expected md5 sum: f998c934df4dfc4a43a92d9144a06170
  actual md5 sum: acf55d593f5eb9dd8d7fe3f3824cfd95
```

**Comment by jdblischak** [comment]
@bgruening Could you please:

1. Mark the duplicate tarball as broken https://anaconda.org/conda-forge/r-digest/0.6.16/download/win-64/r-digest-0.6.16-r351h301d43c_0.tar.bz2
1. Merge PR #5 to update this feedstock
1. Restart the failed AppVeyor build for https://github.com/conda-forge/r-htmltools-feedstock/pull/2 (that failed due to this issue)

**Comment by bgruening** [comment]
partly done ...

**Comment by jdblischak** [comment]
@bgruening Thanks! I confirmed on my Windows machine that r-digest-0.6.16-r351h301d43c_0 can be installed now:

```
conda create -n digest r-digest=0.6.16=r351h301d43c_0
```
